apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapid-v2
  labels:
    app: webapid
    version: v2
spec:
  selector:
    matchLabels:
      version: v2
      app: webapid
  replicas: 1
  template:
    metadata:
      labels:
        version: v2
        app: webapid
    spec:
      containers:
      - name: webapid
        image: moustafarai/webapid:2.0.0
        resources:
          requests:
            cpu: "200m"
            memory : "200Mi"
          limits:
            cpu: "0.4"
            memory : "201Mi"
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: webapid
  labels:
    app: webapid
    service: webapid
spec:
  ports:
  - port: 80
  selector:
    app: webapid
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webapid
  labels:
    account: webapid