apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapia-v3
  labels:
    app: webapia
    version: v3
spec:
  selector:
    matchLabels:
      app: webapia
      version: v3
  replicas: 1
  template:
    metadata:
      labels:
        app: webapia
        version: v3
    spec:
      containers:
      - name: webapia
        image: moustafarai/webapia:3.0.0
        resources:
          requests:
            cpu: "200m"
            memory : "200Mi"
          limits:
            cpu: "0.4"
            memory : "201Mi"
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: webapia
  labels:
    app: webapia
    service: webapia
spec:
  ports:
  - port: 80
  selector:
    app: webapia
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webapia
  labels:
    account: webapia