apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monapplication
  name: webapid-v2
  labels:
    app: webapid
    version: v2
spec:
  selector:
    matchLabels:
      version: v2
      app: webapid
  replicas: 1
  template:
    metadata:
      labels:
        version: v2
        app: webapid
    spec:
      serviceAccountName: webapid
      containers:
      - name: webapid
        image: moustafarai/webapid:2.0.0
        resources:
          requests:
            cpu: "200m"
            memory : "200Mi"
          limits:
            cpu: "0.4"
            memory : "201Mi"
        ports:
        - containerPort: 80
          protocol: TCP