apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapib-v3
  labels:
    app: webapib
    version: v3
spec:
  selector:
    matchLabels:
      app: webapib
      version: v3
  replicas: 1
  template:
    metadata:
      labels:
        app: webapib
        version: v3
    spec:
      containers:
      - name: webapib
        image: moustafarai/webapib:3.0.0
        resources:
          requests:
            cpu: "200m"
            memory : "200Mi"
          limits:
            cpu: "0.4"
            memory : "201Mi"
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: webapib
  labels:
    app: webapib
    service: webapib
spec:
  ports:
  - port: 80
  selector:
    app: webapib
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webapib
  labels:
    account: webapib