apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monapplication
  name: webapid-v1
  labels:
    app: webapid
    version: v1
spec:
  selector:
    matchLabels:
      app: webapid
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: webapid
        version: v1
    spec:
      serviceAccountName: webapid
      containers:
      - name: webapid
        image: moustafarai/webapid:1.0.0
        resources:
          requests:
            cpu: "200m"
            memory : "200Mi"
          limits:
            cpu: "0.4"
            memory : "201Mi"
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  namespace: monapplication
  name: webapid
  labels:
    app: webapid
    service: webapid
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: webapid
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: monapplication
  name: webapid
  labels:
    account: webapid